= LLM Model Configuration

This document describes the available configuration properties for setting up different chat models, the supported APIs, and the default values for each parameter.

== Supported APIs

The following AI providers are currently supported: *OpenAI*, *Mistral AI* and *Anthropic*.

== Configuration of Properties

Each agent can be configured via system properties.
The definition of properties follows the convention:

`-D<model-provider>-api-key=<api-key>`

`-D<agent-type>-agent=<model-provider>`

`-D<agent-type>-model-name=<model>`

where:

- `<model-provider>` can be `open-ai`, `mistral-ai`, or `anthropic`.
- `<api-key>` is your api key.
- `<agent-type>` is one of `reason`, `tooling`.
- `<model>` is the specific model name, (default: `gpt-4o` for OpenAI, `mistral-large-latest` for Mistral, `claude-3-haiku-20240307` for Anthropic).

=== Purpose of each Agent

- *Reason Agent:* Used for computing a representation based on the user prompt and the diagram context.

- *Tooling Agents*:
    * *Orchestration Agent:* Used for orchestrating multiple agents in order to create a diagram based on the representation computed by the reason agent.

    * *Diagram Agents:* Used for generating and deleting diagram elements.

    * *Edition Agents:* Used for object and link editing.

== Example Usage

[source,sh]
----
java --spring.datasource.url=jdbc:postgresql://localhost:5433/sirius-web-db \
     --spring.datasource.username=dbuser \
     --spring.datasource.password=dbpwd \
     -Dmistral-ai-api-key=yourMistralApiKey \
     -Dopen-ai-api-key=yourOpenAiApiKey \
     -Dreason-agent=mistral-ai \
     -Dreason-agent-model-name=mistral-small-latest \
     -Dtooling-agent=open-ai \
     -Dtooling-agent-model-name=gpt-3.5-turbo \
     -jar sirius-web.jar
----
